---
apiVersion: v1
kind: Secret
metadata:
  name: supabase
  namespace: flux-system
stringData:
  identity: |
    -----BEGIN PRIVATE KEY-----
    MIG2AgEAMBAGByqGSM49AgEGBSuBBAAiBIGeMIGbAgEBBDCyqTwS6bRC8iOWisLX
    KtCeQBzyvjKuzDK0k06roRg2Mb3jbtZ1v0MJP27qKkKvY6KhZANiAATSkrNzoPTG
    7OenY9LSDL29tBX7STMuQHJ9TSTH7W6B607gGyghDU7TlJ7kc+O6LKL8yZ5q+kfB
    EbFk/B5mcc1D00E2tzNwDyMTkzMR9CXUMWXZzHDGwGO9kIGDwVpZV1E=
    -----END PRIVATE KEY-----
  identity.pub: |
    ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBNKSs3Og9Mbs56dj0tIMvb20FftJMy5Acn1NJMftboHrTuAbKCENTtOUnuRz47osovzJnmr6R8ERsWT8HmZxzUPTQTa3M3APIxOTMxH0JdQxZdnMcMbAY72QgYPBWllXUQ==
  known_hosts: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=

