---
apiVersion: v1
kind: Secret
metadata:
  name: supabase
  namespace: flux-system
stringData:
  identity: |
    -----BEGIN PRIVATE KEY-----
    MIG2AgEAMBAGByqGSM49AgEGBSuBBAAiBIGeMIGbAgEBBDBkCk5v7TbtnGXaqeHt
    klfnzfLedQckiuQ40yJJkyaOohlN45068834az+NtvXdLC2hZANiAAQbHu1rnTU+
    4tcqxsqLANhCGgOAWHJuP9Ug9nLbo/nb6UIou5Pnh1dj8vH2QsrQFIz475+hPoDh
    OrjIA87mJe629RDhyfDOh1Xwz8pk9usVFtw0tUZUk0qUwFgiSEBcjOw=
    -----END PRIVATE KEY-----
  identity.pub: |
    ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBBse7WudNT7i1yrGyosA2EIaA4BYcm4/1SD2ctuj+dvpQii7k+eHV2Py8fZCytAUjPjvn6E+gOE6uMgDzuYl7rb1EOHJ8M6HVfDPymT26xUW3DS1RlSTSpTAWCJIQFyM7A==
  known_hosts: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=

